apiVersion: v1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1beta1/instance
  labels:
    testing.upbound.io/example-name: example-dbinstance
  name: example-dbinstance
  namespace: upbound-system
type: Opaque
stringData:
  password: "Upbound!"